package LexicalAnalyzer;

public enum TokenType {
    DEF, ID, FOR, IF, ELSE, TRUE, FALSE, DOT, COMMA, SEMICOLON,
    ROUND_OPEN_BRACKET, ROUND_CLOSED_BRACKET,
    CURLY_OPEN_BRACKET, CURLY_CLOSED_BRACKET, SQUARE_OPEN_BRACKET,
    SQUARE_CLOSED_BRACKET, EQUAL, NUMBER, MINUS, PLUS, AND, OR, LESSER,
    GREATER, LESSER_EQUAL, GREATER_EQUAL, MULTIPLY, DIVIDE,
    ASSIGN, NOT_EQUALS, NEGATION, EOF
}
